#dynamic_title = true

[colors.primary]
background = "#1c1917"
foreground = "#ededed"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "FiraMono Nerd Font"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
save_to_clipboard = false

[shell]
program = "/bin/bash"

[window]
decorations = "none"
